Fix test/functional/test_container.py:TestContainer.test_PUT_metadata
Previously, it would fail with

   Traceback (most recent call last):
     File ".../test/functional/test_container.py", line 227, in test_PUT_metadata
       self.assertIsNone(resp.getheader('x-container-meta-test'))
   AssertionError: '' is not None

...because we were actually writing the blank-valued metadata.